algo: ppo
all_train: false
allegro: false
graphics_device_id: cuda:0
headless: true
identifier: bottle_cap
logger_dir: /home/hanminghao/Project/VTDexManip/runs/BottleCap/bottle_cap/bottle_cap-vt_dinov2/seed111
models:
  clip_actions: 1.0
  clip_observations: 5.0
  encoder:
    emb_dim: 128
    en_mode: cls
    f_ex_mode: MAP
    freeze: true
    name: dinov2
    pretrain_dir: model/vitac/model_and_config
  learn:
    agent_name: shadow_hand
    asymmetric: false
    cliprange: 0.2
    desired_kl: 0.016
    ent_coef: 0
    gamma: 0.96
    init_noise_std: 0.8
    lam: 0.95
    log_interval: 1
    max_grad_norm: 1
    max_iterations: 2500
    max_len: 200
    n_per_env: 8
    nminibatches: 4
    noptepochs: 10
    nsteps: 32
    optim_stepsize: 0.0003
    print_log: true
    resume_model: ''
    save_interval: 100
    schedule: adaptive
    test: false
  policy:
    activation: elu
    actor_critic: ActorCriticVEncoderT
    emb_norm: false
    pi_hid_sizes:
    - 1024
    - 1024
    - 512
    vf_hid_sizes:
    - 1024
    - 1024
    - 512
  seed: 111
  torch_deterministic: false
  using_gpu: true
num_gpus: 1
physics_engine: physx
pipeline: cpu
resume_model: ''
rl_device: cuda:0
seed: 111
sim_device: cpu
task: bottle_cap-vt_dinov2
task_envs:
  env:
    actionPenaltyScale: -0.0002
    action_dim: 20
    actionsMovingAverage: 1.0
    aggregateMode: 1
    all_env_path: asset/bottlecap/urdf/obj_info/obj_train_test_split.json
    asset:
      assetFileNameObj: /bottlecap
      assetFileNameRobot: shadow_hand/mjcf/open_ai_assets/hand/shadow_hand_bottle.xml
      assetRoot: ./asset
    asymmetric_observations: false
    clip_actions: 1.0
    clip_observations: 5.0
    controlFrequencyInv: 1
    distRewardScale: 20
    dofSpeedScale: 20.0
    enableDebugVis: true
    enableDisReward: true
    enableTouchReward: true
    enable_soft_contact: false
    envSpacing: 1.5
    env_dict:
    - core-bottle-2722bec1947151b86e22e2d2f64c8cef
    - core-bottle-91235f7d65aec958ca972daa503b3095
    - core-bottle-add17b35bc4665e6f33a685c2506bbe6
    - core-bottle-b8767b71c2216dcad317c475f024f3b8
    - core-bottle-cf0a733f9a63f4f5664b3b9b23ddfcbc
    - core-bottle-cf7a79435eb5b1bdb0be98650cd7fb6f
    - core-bottle-ed55f39e04668bf9837048966ef3fcb9
    - core-bottle-fda8d8820e4d166bd7134844380eaeb0
    - core-bottle-77a2242bf4ea8f9fc02fe00a7187a6a9
    - core-bottle-d8021dc9fc9109b130612f5c0ef21eb8
    episodeLength: 500
    fallDistance: 0.4
    fallPenalty: 0.0
    fixed_hand: true
    forceLimitScale: 1.0
    frame_skip: 4
    full_obs: false
    goal_height:
    - 0.16
    - 0.16
    - 0.15
    - 0.155
    - 0.16
    - 0.155
    - 0.165
    - 0.165
    - 0.16
    - 0.16
    hand_bias:
    - -0.38
    - -0.02
    - 0.0
    hand_init_height:
    - 0.23
    - 0.23
    - 0.23
    - 0.23
    - 0.23
    - 0.23
    - 0.23
    - 0.23
    - 0.23
    - 0.23
    img_h: 224
    img_w: 224
    maxConsecutiveSuccesses: 0
    min_contacts: 1
    n_env_repeat: 1
    numEnvs: 200
    objectType: block
    object_init_height:
    - 0.09
    - 0.09
    - 0.09
    - 0.09
    - 0.09
    - 0.09
    - 0.09
    - 0.09
    - 0.09
    - 0.09
    object_scale:
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    obs_dim:
      prop: 48
      tac: 20
      vis: 150528
    obs_type: VisTac
    observationType: full_state
    orientation_scale: 0.1
    printNumSuccesses: false
    random_load:
      a: 2
      b: 2
      num_obj_per_env: 1
      obj_width: 0.1
      sequential: true
    random_prior: true
    reachGoalBonus: 250
    repose_z: true
    resetDofPosRandomInterval: 0.05
    resetDofVelRandomInterval: 0.1
    resetPositionNoise: 0.0
    resetRotationNoise: 0.0
    reward_weight:
    - 0.5
    - 1
    - 0.5
    - 0
    rotEps: 0.1
    rotRewardScale: 1.0
    startPositionNoise: 0.01
    startRotationNoise: 0.0
    stiffnessScale: 1.0
    successTolerance: 0.1
    success_type: one
    tac_theshold: 0.01
    transition_scale: 0.5
    useRelativeControl: false
    vision:
      camera:
        eye:
        - - -0.25
          - 0.35
          - 0.5
        lookat:
        - - 0.02
          - -0.02
          - 0.1
  sim:
    dt: 0.01667
    physx:
      always_use_articulations: false
      bounce_threshold_velocity: 0.2
      contact_offset: 0.005
      default_buffer_size_multiplier: 5.0
      max_depenetration_velocity: 1000.0
      num_position_iterations: 12
      num_threads: 4
      num_velocity_iterations: 1
      rest_offset: 0.0
      solver_type: 1
    substeps: 1
  task:
    randomization_params:
      actions:
        distribution: gaussian
        operation: additive
        range:
        - 0.0
        - 0.05
        range_correlated:
        - 0
        - 0.015
        schedule: linear
        schedule_steps: 40000
      frequency: 500
      observations:
        distribution: gaussian
        operation: additive
        range:
        - 0
        - 0.002
        range_correlated:
        - 0
        - 0.001
        schedule: linear
        schedule_steps: 40000
    randomize: true
  task_description: screw bottle cap for opening or closing
  task_name: BottleCap
  video_path: /videos
test: false
